### ISSUE TITLE
Missing suffix in 1001 element in HCPB_1D_ITER and WCLL_1D_ITER

### ISSUE THREAD

**Issue by Radiation-Transport** [dodu94/JADE#153]
Missing suffix in 1001 element at least in HCPB_1D_ITER and WCLL_1D_ITER.
It seems it appears if only 1001 is the first element. Quite strange.

![Capture](https://user-images.githubusercontent.com/48320561/158962463-01b85d26-063e-484b-b3dc-a32bff61f524.JPG)

**Comment by dodu94** [comment]
This is most likely due to an error in the xsdir file. If the line for 1001.00c is missing and 00c is set as the default library the code will not find any viable solution for the translation (raising an error). The fact that 1001 is the first isotope appearing in the xsdir further convince me that this is indeed the issue. Please re-open if that was not the case.
